spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://192.168.56.10:5432/postgres
    password: '1234'
    
  mvc:
    hiddenmethod:
      filter:
        enabled: true
   
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Temp
      max-file-size: 100MB
      max-request-size: 100MB
    
   

